- Gruntfile-SoCraTes.js
- config/beans-socrates.json
- socrates/app.js
- socrates/lib/mailsender/index.js
- socrates/lib/mailsender/views/compose.jade
- socrates/lib/mailsender/views/mailsender-forms.jade
- socrates/lib/members/views/get.jade
- socrates/locales/translation-en.json
- softwerkskammer/lib/mailsender/mailsenderService.js
- softwerkskammer/locales/translation-de.json
- softwerkskammer/locales/translation-en.json
> Member edit button and mail-sending on member page 

- .idea/runConfigurations/Activities.xml
- config/beans-socrates.json
- socrates/lib/registration/index.js
- socrates/lib/registration/registrationService.js
- socrates/lib/registration/socratesResource.js
- socrates/lib/registration/views/participate.jade
- socrates/lib/registration/views/participationinfoform.jade
- socrates/test/registration/socratesResource_object_test.js
- softwerkskammer/lib/activities/activitiesService.js
- softwerkskammer/lib/activities/index.js
- softwerkskammer/lib/activities/resource.js
- softwerkskammer/lib/activities/resourceRegistrationRenderer.js
- softwerkskammer/lib/activities/views/get.jade
- softwerkskammer/lib/mailsender/mailsenderService.js
- softwerkskammer/lib/members/member.js
- softwerkskammer/test/activities/activitiesService_test.js
- softwerkskammer/test/activities/activities_test.js
- softwerkskammer/test/activities/activity_object_resource_test.js
- softwerkskammer/test/activities/resource_object_test.js
- softwerkskammer/test/activities/resources_object_test.js
- softwerkskammer/test/members/member_object_test.js
- Various bugfixes
- Preparations for activity subscribe GET -> POST (subscription from waitinglist)
- First step towards SoCraTes registration
> Lots of stuff

- softwerkskammer/lib/groups/views/get.jade
Die "Kommenden Aktivitäten" werden vor der Tag Cloud angezeigt.
> 915: Vorschlag Aktivitätenliste vor der Tag Cloud

- .gitattributes
- syncLocalCopy.sh
For vagrant under Windows
cd /vagrant
./syncLocalCopy
cd /home/vagrant/agora
npm install
Execute ./syncLocalCopy every time to update its content (.git is linked but the rest is copied)
https://github.com/softwerkskammer/Agora/issues/924
> Script to create and synchronize folder /home/vagrant/agora when vagrant runs under windows

- socrates/lib/activities/index.js
- socrates/lib/activities/socratesActivitiesService.js
- socrates/lib/activities/socratesResource.js
- socrates/lib/registration/views/get.jade
- socrates/lib/registration/views/managementTables.jade
- socrates/test/activities/socratesActivitiesService_test.js
- socrates/test/activities/socratesResource_object_test.js
- socrates/test/registration/registration_test.js
> Waitinglist people can now be turned into participants

- socrates/lib/registration/views/participationinfoform.jade
There was some confusion whether the length of a junior bed is only 160cm. The hotel website states that a junior bed is 160cm in width :-) this should clear up some confusion :)
> Mention dimension of bed of junior bedrooms

- README.md
- config/example-wikirepo-config.json
- softwerkskammer/lib/mailsender/message.js
- softwerkskammer/test/mailsender/message_object_test.js
https://github.com/softwerkskammer/Agora/issues/910
> Add public URL prefix to links in generated e-mail messages + docu

- config/beans-socrates.json
- socrates/app.js
- socrates/configure.js
- socrates/lib/mailsender/index.js
- socrates/lib/middleware/accessrights.js
- socrates/lib/middleware/secureSoCraTesAdminOnly.js
- socrates/lib/registration/views/managementTables.jade
- socrates/lib/site/index.js
- socrates/lib/site/views/socratesAdminRightsRequired.jade
- socrates/test/mailsender/mailsender_test.js
- socrates/testutil/abstractConfigureForTest.js
- softwerkskammer/lib/middleware/secureSuperuserOnly.js
- softwerkskammer/testutil/universalTestHelper.js
- softwerkskammer/testutil/userStub.js
> SoCraTes Admin

- socrates/lib/site/views/location.jade
Updated content, but probably still needs some visual touches.
The actions post merge:
- "delete" https://www.socrates-conference.de/wiki/2015/directions-to-the-venue
- update links to wiki-directions
> Update location page with directions to venue

- .idea/copyright/profiles_settings.xml
- .idea/misc.xml
- socrates/testutil/abstractConfigureForTest.js
- softwerkskammer/lib/commons/renderer.js
- softwerkskammer/test/commons/renderer_test.js
- softwerkskammer/test/wiki/wiki_test.js
- softwerkskammer/testutil/abstractConfigureForTest.js
and some other bits and pieces.
> Some corrections to the iconv-lite conversion

- locales/translation-de.json
- socrates/lib/activities/socratesActivitiesService.js
- socrates/lib/activities/socratesConstants.js
- socrates/lib/members/index.js
- socrates/lib/registration/managementService.js
- socrates/lib/subscribers/subscriberService.js
- socrates/lib/subscribers/subscriberstore.js
- socrates/test/activities/socratesActivitiesService_test.js
- socrates/test/members/members_test.js
- socrates/test/subscribers/subscriberService_test.js
- softwerkskammer/lib/groupsAndMembers/groupsAndMembersService.js
- softwerkskammer/lib/middleware/redirectRuleForNewUser.js
- softwerkskammer/test/restricted-access/special_access_test.js
- softwerkskammer/testWithDB/activitiesDB/activities_for_groupids_test.js
- furthermore "socrates-only" members will no be _forced_ to save their profile in softwerkskammer
> FEATURE: SoCraTes subscribers can now be deleted

- package.json
- softwerkskammer/lib/middleware/expressSessionConfigurator.js
- softwerkskammer/lib/middleware/handle500.js
- additionally add some extra exception logging
- version bumps
> remove nasty mongodb (bson) warning

- README.md
- package.json
1. Installation description updated 
2. npm start script changed to "node start-softwerkskammer"
> Little update about how to install Agora for contributing to it

- README.md
- config/example-socrates-server-config.json
- socrates/lib/registration/views/participationinfoform.jade
Fix #1045 (Broken link)
participationinfoform.jade changed. This year we don't need a deposit.
> Deposit thema and broken link fix

- socrates/lib/site/views/index.jade
dieses Mal nach Datum einsortiert :)
> add partner conference 'JS CraftCamp' at correct position

- socrates/lib/site/views/index.jade
After discussing this with Nicole Rauch, I added a link to SoCraTes Day Linz to the front page.
> Added link to SoCraTes Day Linz 2016

- .travis.yml
- softwerkskammer/lib/persistence/persistence.js
- softwerkskammer/testWithDB/persistence/issue-1105.js
This fixes softwerkskammer/Agora#1105
> test(testWithDB): fix mocha_istanbul:testWithDB fails on MongoDB v3.2.9

- softwerkskammer/lib/mailsender/index.js
- softwerkskammer/lib/mailsender/mailsenderService.js
- softwerkskammer/lib/mailsender/message.js
- softwerkskammer/test/mailsender/mailsenderService_test.js
(see also Agora-Backlog/issues/150)
> adding the ical file to activity mails

- socrates/lib/eventstore/GlobalEventStore.js
- socrates/lib/eventstore/RegistrationCommandProcessor.js
- socrates/lib/eventstore/RegistrationReadModel.js
- socrates/lib/eventstore/RegistrationWriteModel.js
- socrates/lib/eventstore/RoomsCommandProcessor.js
- socrates/lib/eventstore/RoomsReadModel.js
- socrates/lib/eventstore/RoomsWriteModel.js
- socrates/lib/eventstore/SoCraTesCommandProcessor.js
- socrates/lib/eventstore/SoCraTesReadModel.js
- socrates/lib/eventstore/SoCraTesWriteModel.js
- socrates/lib/eventstore/eventstoreService.js
- socrates/test/activities/activities_test.js
- socrates/test/activities/activityParticipantService_test.js
- socrates/test/activities/roomOptions_test.js
- socrates/test/activities/socratesActivitiesService_test.js
- socrates/test/eventstore/RegistrationCommandProcessor_test.js
- socrates/test/eventstore/RegistrationReadModel_test.js
- socrates/test/eventstore/RoomsCommandProcessor_test.js
- socrates/test/eventstore/RoomsReadModel_test.js
- socrates/test/eventstore/SoCraTesReadModel_test.js
- socrates/test/eventstore/eventstoreService_test.js
- socrates/test/eventstore/eventstore_test.js
- socrates/test/members/members_test.js
- socrates/test/members/socratesMembersService_test.js
- socrates/test/registration/managementService_test.js
- socrates/test/registration/registrationService_test.js
- socrates/test/registration/registration_test.js
- softwerkskammer/migrateDB.js
Now all events are stored in the same list. **ATTENTION**: Requires DB migration on deploy. (Shut down SoCraTes for this pls.)
> Unification of event lists

- .travis.yml
This lets travis post to the [#agora_build_monitor](https://softwarecraftsmanship.slack.com/messages/agora_build_monitor/) channel.
> Update Slack notification settings

- softwerkskammer/lib/wiki/gitExec.js
- softwerkskammer/lib/wiki/gitmech.js
- softwerkskammer/test/wiki/gitmech_test.js
* Now the async call to git has a callback (previously it was an async call that was executed inline! That's why the SoCraTes wiki notification mail would sporadically fail)
* Now all checks (of repo and git binary) are done when the application starts
Please run some manual smoketests if possible (I did that, too) - maybe even on Windows...?
> Rewrite of Git module

- locales/translation-de.json
- locales/translation-en.json
- softwerkskammer/lib/dashboard/index.js
- softwerkskammer/lib/dashboard/views/index.pug
- softwerkskammer/lib/dashboard/views/indexJson.pug
- softwerkskammer/views/layoutComponents.pug
It will require log-in. - So if not logged-in the user is requested to do so.
> Integrate the dashboard into the main menu

- softwerkskammer/configure.js
- softwerkskammer/googleOnlyUsers.js
- softwerkskammer/lib/activities/activitiesService.js
- softwerkskammer/lib/activities/activity.js
- softwerkskammer/lib/activities/activitystore.js
I hope this goes in the right direction
> starting to remove lodash dependency / ES6ifying code

- softwerkskammer/lib/wiki/wikiService.js
This hopefully fixes bug #1135
> Limit the number of parallel git commands

- .eslintrc
- socrates/lib/activities/index.js
- socrates/lib/eventstore/SoCraTesCommandProcessor.js
- socrates/lib/eventstore/eventstoreService.js
- socrates/test/activities/activities_test.js
- socrates/test/eventstore/SoCraTesCommandProcessor_test.js
> Now a new SoCraTes has the correct URL

- Gruntfile.js
- package.json
mini change for softwerkskammer only
> replacing jqcloud dependency by the "original" instead of mine

- socrates/lib/activities/activityParticipantService.js
- socrates/lib/eventstore/RegistrationReadModel.js
- socrates/lib/eventstore/RegistrationWriteModel.js
- socrates/lib/eventstore/eventstoreService.js
- socrates/lib/registration/index.js
- socrates/lib/registration/views/managementTables.pug
- socrates/test/activities/socratesActivitiesService_test.js
- socrates/test/eventstore/RegistrationCommandProcessor_test.js
- socrates/test/eventstore/RegistrationReadModel_test.js
- socrates/test/eventstore/RegistrationWriteModel_test.js
- socrates/test/eventstore/RoomsCommandProcessor_test.js
- socrates/test/eventstore/RoomsReadModel_test.js
- socrates/test/eventstore/eventstoreService_test.js
- socrates/test/registration/managementService_test.js
- socrates/test/registration/registrationService_test.js
Now each of them has their own model which gets directly calculated from the events.
> Breaking up the dependency between Registration Read and Write models

- softwerkskammer/lib/groups/ezmlmAdapter.js
- softwerkskammer/lib/groups/fakeListAdapter.js
- softwerkskammer/lib/groups/group.js
- softwerkskammer/lib/groups/groupsService.js
- softwerkskammer/lib/groups/groupstore.js
- softwerkskammer/lib/groups/index.js
- softwerkskammer/lib/groupsAndMembers/groupsAndMembersService.js
- softwerkskammer/test/groups/ezmlmAdapterTest.js
- softwerkskammer/test/groups/group_object_test.js
- softwerkskammer/test/groups/groupsService_subscription_test.js
- softwerkskammer/test/groups/groupsService_test.js
- softwerkskammer/test/groups/groups_for_tests.js
- softwerkskammer/test/groups/groups_test.js
- softwerkskammer/test/groups/groupstore_test.js
> Boy Scouting Groups

- softwerkskammer/lib/mailarchive/importMails.js
Was meinst Du dazu?
- Mit gefällt, dass es weniger files sind und das `request(app)` nur noch einmal da ist.
> minor streamlining in importMails

- softwerkskammer/lib/administration/index.js
- softwerkskammer/lib/administration/views/memberTable.pug
- softwerkskammer/lib/members/updateAvatarData.js
- softwerkskammer/lib/members/views/editavatar.pug
- softwerkskammer/lib/wiki/gitmech.js
- softwerkskammer/lib/wiki/wikiService.js
- softwerkskammer/test/wiki/eventsToObject_test.js
- softwerkskammer/test/wiki/gitmech_test.js
> fix for #1195

- locales/translation-de.json
- locales/translation-en.json
- softwerkskammer/lib/authentication/index.js
- softwerkskammer/lib/site/index.js
- softwerkskammer/lib/site/views/loginDialog.pug
> Login choice

- socrates/lib/activities/socratesActivitiesService.js
- socrates/lib/notifications/index.js
- socrates/lib/notifications/pug/roomPairConfirmation.pug
- socrates/lib/notifications/pug/roomPairRemoval.pug
- socrates/lib/notifications/pug/superuserRoomPairNotification.pug
- socrates/lib/notifications/pug/superuserRoomPairRemovalNotification.pug
- socrates/test/notifications/notifications_test.js
> Mails when a room pair is added or removed

- softwerkskammer/views/googlemaps-component.pug
> fixing the new _awkward_ behaviour of googlemaps API

- socrates/lib/registration/nametagService.js
- socrates/test/registration/nametagService_test.js
- for orcana size
- slightly improved the produced '.tex'
> TeX template generation optimized

- commonComponents/frontend-js/frontendutils.js
> datepicker now always drops DOWN not AUTO

- softwerkskammer/lib/commons/renderer.js
- softwerkskammer/lib/wiki/views/wiki-mixins.pug
- softwerkskammer/test/wiki/wikiObjects_test.js
- softwerkskammer/test/wiki/wikiService_test.js
> Blogpost correction

- socrates/lib/authentication/index.js
- softwerkskammer/lib/authentication/authenticationService.js
- softwerkskammer/lib/members/membersService.js
- softwerkskammer/test/authentication/authenticationService_test.js
- softwerkskammer/test/members/membersService_test.js
... because we don't need it any more.
> Removed the legacy authentication method

- socrates/views/layoutComponents.pug
The twitter handle and the date in the tweet template were out-of-date.
> Update SoCraTes twitter stuff

- socrates/lib/site/views/sponsoring.pug
The sponsoring table needs to be updated according to the commited sponsoring types. (750€ per sponsored participant, max. 5 sponsored participants)
> Update sponsoring table

- INSTALL.md
Added info on using Homebrew to install missing dependencies on Mac OS.
> Install info MacOS

- socrates/lib/site/index.js
- socrates/lib/site/views/access.pug
- socrates/lib/site/views/values.pug
- socrates/views/layoutComponents.pug
New accessibility page and links to it from navigation and values page.
> New accessibility page

- socrates/lib/members/index.js
- socrates/lib/members/memberSubmitHelper.js
- socrates/lib/members/views/get.pug
- socrates/lib/middleware/accessrights.js
- socrates/lib/wiki/views/participants.pug
- socrates/test/members/members_test.js
- driver: undeliverable emails
> superusers can now edit other socrates member's profiles

- socrates/lib/registration/views/managementTables.pug
- socrates/lib/subscribers/addon.js
- socrates/lib/subscribers/subscriber.js
- socrates/test/subscribers/addon_object_test.js
- socrates/test/subscribers/subscriber_object_test.js
Include values in "preferred pronoun" in waiting list and for automatic diversity evaluation
> Updated diversity evaluation for tonight's lottery

- socrates/lib/site/sponsors.json
> fix novatec sponsor link

- socrates/lib/site/partners.json
Would be great to have our first SoCraTes Day in Berlin listed as a partner conference 👋
> Add SoCraTes Day Berlin to list of partner confs

- package.json
- softwerkskammer/lib/activities/index.js
- softwerkskammer/views/layout.pug
- also updated uglify for faster conversion
> introduced this year's gdcr and 2018 events

- package.json
in the hope that this maybe addresses our obnoxious "MongoError: failed to connect to server on first connect" that happens in prod every so often.
Tests are green, and I clicked around everywhere. So I believe this is good :-)
> Updating mongodb driver 

- softwerkskammer/app.js
- softwerkskammer/lib/groups/index.js
- softwerkskammer/views/commonLayout.pug
Follow-up on https://github.com/softwerkskammer/Agora/pull/1312#issuecomment-374047335.
> Add site title, favicon and logo to group blogpost Atom feeds

- softwerkskammer/lib/groups/index.js
> Fix URLs in Atom feed

- .gitignore
- INSTALL.md
Remove some outdated information and ease initial setup
> Small cleanups

- dev-goodies/mongo snippets.txt
- softwerkskammer/lib/activities/activity.js
- softwerkskammer/lib/activities/activitystore.js
- softwerkskammer/test/activities/activities_store_test.js
- softwerkskammer/test/activities/activities_test.js
- softwerkskammer/test/activities/activity_fillFromUI_test.js
- softwerkskammer/test/activities/activity_object_test.js
- softwerkskammer/test/activities/calendarService_test.js
- softwerkskammer/test/administration/administration_test.js
- softwerkskammer/test/groups/groups_test.js
- softwerkskammer/test/mailsender/mailsenderService_test.js
- softwerkskammer/test/middleware/accessrights_test.js
- softwerkskammer/testWithDB/activitiesDB/activities_for_groupids_test.js
- softwerkskammer/testWithDB/activitiesDB/activities_for_organziers_and_editors_test.js
- softwerkskammer/testWithDB/activitiesDB/activities_index_concurrency_test.js
- softwerkskammer/testWithDB/activitiesDB/activities_index_upcoming_past_test.js
- softwerkskammer/updateActivitiesWithPersistentDates.js
- after updating run script updateActivitiesWithPersistentDates.js with node parameter ```--icu-data-dir=node_modules/full-icu``` (or the right path for your system)
- next step will then bi to eliminate startUnix and endUnix completely in code and Mongo
> removal of startUnix and endUnix

- softwerkskammer/lib/members/updateAvatarData.js
- softwerkskammer/lib/persistence/persistence.js
Implementierung angepasst. Gemäß Doku. Lokal getestet
> changing implementation of "close" with mongoDB

- softwerkskammer/lib/members/updateAvatarData.js
- softwerkskammer/lib/wiki/createChangeNotifications.js
to avoid getting emails for successful avatar updates and wiki
notification sends only error cases are logged
In order to still be informed if they ran at all I set up separate cron
jobs to send out "lastrun" information for which I extended the
corresponding shell scripts (not part of this repo, only on the server).
> Only error log for cron mail

- config-examples/mailsender-config.json
- softwerkskammer/lib/mailsender/mailsenderService.js
- softwerkskammer/lib/mailsender/mailtransport.js
- softwerkskammer/lib/mailsender/message.js
- softwerkskammer/lib/mailsender/views/mailtemplate-textonly.pug
- softwerkskammer/lib/mailsender/views/mailtemplate.pug
- softwerkskammer/test/mailsender/message_object_test.js
Hier mal ein erster Entwurf für #1428:
* beim konkreten Text des Footers nehme ich gerne noch Vorschläge an :-)
* falls der Pug-Code komisch oder falsch ist: ich kenne mich damit nicht so aus und habe gerade bei der HTML-Variante des Mail-Templates ziemlich gekämpft :-/
* Test-Mail habe ich noch nicht versendet, wollte erstmal Feedback abwarten, aber die Tests zeigen zumindest, dass es gehen sollte :-)
Fixes #1428
> E-Mail-Footer um DeltaTree zu danken

- package-lock.json
accidentally removed package-lock.json
> update deps deep

- config-examples/mailsender-config.json
- config-examples/winston-config.json
- softwerkskammer/lib/mailsender/nodemailer-logger.js
- softwerkskammer/lib/mailsender/nodemailerTransport.js
To troubleshoot #1456 we redirect the logging from nodemailer to winston
We did not manage to get the local mail setup working, can you help with a quick test?
> Redirect nodemailer logging to winston

- softwerkskammer/lib/mailsender/mailtransport.js
- softwerkskammer/lib/mailsender/nodemailerTransport.js
- fix broken import
- add success logging to sendMail
> Fix mail debug logging
